version: 0.0
os: linux
files:
  - source: backend/code-database
    destination: /home/ubuntu/code-database/build
  - source: backend/.env
    destination: /home/ubuntu/code-database/build
  - source: backend/dist
    destination: /home/ubuntu/code-database/build/dist
  - source: frontend/public
    destination: /home/ubuntu/code-database/build/public
  - source: backend/xml_update
    destination: /home/ubuntu/code-database/build
  - source: infrastructure/deploy/google_sitemap
    destination: /home/ubuntu/code-database/build/google_sitemap

permissions:
  - object: /home/ubuntu
    pattern: "code-database"
    owner: ubuntu
    group: ubuntu
    type:
      - directory
  - object: /home/ubuntu/code-database/build/xml_update
    owner: ubuntu
    group: ubuntu
    type:
      - file

hooks:
  ApplicationStop:
    - location: infrastructure/deploy/scripts/stop.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: infrastructure/deploy/scripts/start.sh
      timeout: 300
      runas: ubuntu