version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    commands:
      - apt update -y
      - apt install make -y
  build:
    commands:
      - docker-compose run frontend bash -c "npm install && npm run build"
      - docker-compose run backend go build

artifacts:
  files:
    - backend
