version: 0.2

env:
  git-credential-helper: yes
  parameter-store:
    DOCKER_TOKEN: dockerhub-token

phases:
  install:
    commands:
      - apt update -y
  pre_build:
    commands:
      - echo $DOCKER_TOKEN | docker login -u reibomaru --password-stdin
  build:
    commands:
      - make frontend
      - make backend
  post_build:
    commands:
      - echo SQL_ENV=$SQL_ENV >> backend/.env
      - echo SESSION_KEY=$SESSION_KEY >> backend/.env
      - echo BUILD_MODE=$BUILD_MODE >> backend/.env

artifacts:
  files:
    - ./**/*
