name: CI
on: [push]
jobs:
  frontend-lint:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '15.14.0'
      - name: Install node packeages
        run: |
          npm install
      - name: Check format
        run: npm run format-check
      - name: Run lint
        run: |
          npm run lint
      - name: Build
        run: npm run build
  backend-build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0' # The Go version to download (if necessary) and use.
      - name: Build
        run: go build
